- name: Install and Configure Nginx
  hosts: web
  become: yes
  tasks: 
  - name: Install Nginx
    apt:
      name: nginx
      state: present
      update cache: yes

  - name: Start the Nginx
    service: 
      name: nginx
      state: started
      enabled: true
        
